language: c
dist: bionic
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler python3-pip
  - sudo pip3 install protobuf
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
env:
  global:
  - PINS="pb.dev:. pb-plugin.dev:."
  - PACKAGE="pb" OCAML_VERSION=4.03
  - PACKAGE="pb" OCAML_VERSION=4.04
  - PACKAGE="pb" OCAML_VERSION=4.05
  - PACKAGE="pb" OCAML_VERSION=4.06
  - PACKAGE="pb" OCAML_VERSION=4.07
  - PACKAGE="pb" OCAML_VERSION=4.08
  - PACKAGE="pb-plugin" OCAML_VERSION=4.03
  - PACKAGE="pb-plugin" OCAML_VERSION=4.04
  - PACKAGE="pb-plugin" OCAML_VERSION=4.05
  - PACKAGE="pb-plugin" OCAML_VERSION=4.06
  - PACKAGE="pb-plugin" OCAML_VERSION=4.07
  - PACKAGE="pb-plugin" OCAML_VERSION=4.08
script:
  - bash -ex .travis-opam.sh
